apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    isDefault: true
    access: proxy
    url: http://prometheus:9090
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
