services:
  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro

  prometheus:
    image: prom/prometheus:v2.54.1
    ports:
      - "9090:9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention.time=15d
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./alert.rules.yml:/etc/prometheus/alert.rules.yml:ro
      - prometheus-data:/prometheus

  loki:
    image: grafana/loki:2.9.8
    ports:
      - "3100:3100"
    command: ["-config.file=/etc/loki/loki-config.yml"]
    volumes:
      - ./observability/loki-config.yml:/etc/loki/loki-config.yml:ro
      - loki-data:/loki

  promtail:
    image: grafana/promtail:2.9.8
    volumes:
      - ./promtail-config.yml:/etc/promtail/config.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/log:/var/log:ro
      - promtail-positions:/positions

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  pg:
    image: postgres:16
    container_name: pg           # <-- force literal name, prevents tdp-pg-1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: catalog
      POSTGRES_USER: catalog_user
      POSTGRES_PASSWORD: catalog_pass
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  grafana-data:
  prometheus-data:
  loki-data:
  promtail-positions:
  rabbitmq-data:
  pgdata:
