services:
  loki:
    container_name: loki
    image: grafana/loki:2.9.8
    command: -config.file=/etc/loki/config.yml
    volumes:
      # NOTE: this path is relative to THIS file (platform/compose/)
      - ../observability/loki/config.yml:/etc/loki/config.yml:ro
      - loki-data:/loki
    ports:
      - "3100:3100"
    restart: unless-stopped

  grafana:
    container_name: grafana
    image: grafana/grafana:11.2.0
    depends_on:
      loki:
        condition: service_started
      prometheus:
        condition: service_started
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: devopsplayground
      GF_PATHS_PROVISIONING: /etc/grafana/provisioning
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
    restart: unless-stopped

volumes:
  loki-data:
  grafana-data:
