global:
  scrape_interval: 15s
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: loki
    static_configs:
      - targets: ['loki:3100']
  - job_name: rabbitmq
    static_configs:
      - targets: ['rabbitmq:15692']
  - job_name: orders-api
    static_configs:
      - targets:
          - orders-api:8000
        labels:
          env: local
  - job_name: payments-api
    static_configs:
      - targets:
          - payments-api:8000
        labels:
          env: local
  - job_name: node-exporter
    static_configs:
      - targets:
          - host.docker.internal:9100
          - 172.17.0.1:9100
  - job_name: cadvisor
    static_configs:
      - targets:
          - cadvisor:8080
  - job_name: promtail
    static_configs:
      - targets:
          - promtail:9080
  - job_name: catalog-api
    metrics_path: /metrics
    static_configs:
      - targets:
          - catalog-api:8000
  - job_name: ai-worker
    metrics_path: /metrics
    static_configs:
      - targets:
          - ai-worker:9101
  - job_name: inventory-worker
    metrics_path: /metrics
    static_configs:
      - targets:
          - inventory-worker:9102
  - job_name: postgres
    metrics_path: /metrics
    static_configs:
      - targets:
          - postgres-exporter:9187
