name: CI
on:
  push:
    branches: [dev, prod]
  pull_request:
    branches: [dev, prod]
jobs:
  lint:
    name: CI / lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "lint ok"
  build:
    name: CI / build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "build ok"
